# Generated by Django 5.2.1 on 2025-08-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0002_remove_student_marks_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='subject',
        ),
    ]
