# Generated by Django 5.2.1 on 2025-08-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0009_assessment_notice_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='univ.student'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='univ.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='univ.student'),
        ),
    ]
