# Generated by Django 5.2.1 on 2025-08-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0012_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='register_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
