# Generated by Django 5.2.1 on 2025-08-20 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0013_student_duration_student_register_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='univ.student'),
        ),
    ]
